#!/usr/bin/perl

###
# find unique violation from csv for migration.
# usage : 'where source file ' which indexes..
##

use strict;
use warnings;

use Text::CSV_XS;

use vars qw(@PARAM);
@PARAM = @ARGV;
print 'no param..source file and indexes with a space' and exit 1 if ($#PARAM < 1 - 1);

my $header = '';
my $source = shift @PARAM;
my @indexes = split(/ /, shift @PARAM);

my $csv = Text::CSV_XS->new ({ binary => 1 });
open my $fh, "<", "$source";
my $target = ($source =~ tr/[\/ | \.]/_/);
open my $fh_out, ">", "result_${target}.csv";

my @sources = ();
$csv->getline ($fh) if defined($header);
while (not $csv->eof and my $columns = $csv->getline ($fh)) {
	my %duplicate;
	my $skip = 0;

	for my $s (@sources) {
		my @key;
		my $key_joined;
		
		$key_joined = join('_', @key) if grep {unshift(@key, $s->[$_])} (@indexes);
	
		print $fh_out "@$columns\n" if grep {$duplicate{$key_joined} >= $#indexes + 1 + 2 - 1} grep {++$duplicate{$key_joined} if $columns->[$_] eq $s->[$_]} (@indexes) > 0;
	}

	unshift(@sources, $columns);
}

close $fh_out;
close $fh;

